<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    public function run()
    {
        $items = [
            // Flour & Baking Mixes
            [
                'item_id' => 1,
                'item_code' => 'FL001',
                'item_name' => 'All-Purpose Flour',
                'item_description' => 'Premium all-purpose flour for general baking needs',
                'item_unit' => 'kilogram',
                'cat_id' => 1,
                'item_stock' => 500.000,
                'item_expire_date' => '2024-12-31',
                'reorder_level' => 100.000,
                'min_stock_level' => 50.000,
                'max_stock_level' => 1000.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 2,
                'item_code' => 'FL002',
                'item_name' => 'Cake Flour',
                'item_description' => 'Fine cake flour for delicate cakes and pastries',
                'item_unit' => 'kilogram',
                'cat_id' => 1,
                'item_stock' => 25.000,
                'item_expire_date' => '2024-12-31',
                'reorder_level' => 50.000,
                'min_stock_level' => 25.000,
                'max_stock_level' => 500.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 3,
                'item_code' => 'BM001',
                'item_name' => 'Pancake Mix',
                'item_description' => 'Ready-to-use pancake mix for fluffy pancakes',
                'item_unit' => 'kilogram',
                'cat_id' => 1,
                'item_stock' => 75.000,
                'item_expire_date' => '2024-11-15',
                'reorder_level' => 30.000,
                'min_stock_level' => 15.000,
                'max_stock_level' => 200.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Dairy Products
            [
                'item_id' => 4,
                'item_code' => 'DA001',
                'item_name' => 'Fresh Milk',
                'item_description' => 'Fresh whole milk for baking and consumption',
                'item_unit' => 'liter',
                'cat_id' => 2,
                'item_stock' => 200.000,
                'item_expire_date' => '2024-11-20',
                'reorder_level' => 100.000,
                'min_stock_level' => 50.000,
                'max_stock_level' => 500.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 5,
                'item_code' => 'DA002',
                'item_name' => 'Heavy Cream',
                'item_description' => 'Heavy whipping cream for desserts and pastries',
                'item_unit' => 'liter',
                'cat_id' => 2,
                'item_stock' => 40.000,
                'item_expire_date' => '2024-11-18',
                'reorder_level' => 25.000,
                'min_stock_level' => 10.000,
                'max_stock_level' => 100.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 6,
                'item_code' => 'DA003',
                'item_name' => 'Cream Cheese',
                'item_description' => 'Philadelphia cream cheese for cheesecakes',
                'item_unit' => 'kilogram',
                'cat_id' => 2,
                'item_stock' => 15.000,
                'item_expire_date' => '2024-12-01',
                'reorder_level' => 20.000,
                'min_stock_level' => 10.000,
                'max_stock_level' => 50.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Eggs
            [
                'item_id' => 7,
                'item_code' => 'EG001',
                'item_name' => 'Fresh Eggs (Large)',
                'item_description' => 'Grade A large fresh eggs',
                'item_unit' => 'piece',
                'cat_id' => 3,
                'item_stock' => 2400.000,
                'item_expire_date' => '2024-11-25',
                'reorder_level' => 1200.000,
                'min_stock_level' => 600.000,
                'max_stock_level' => 5000.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Sugar & Sweeteners
            [
                'item_id' => 8,
                'item_code' => 'SU001',
                'item_name' => 'Granulated Sugar',
                'item_description' => 'White granulated sugar for general use',
                'item_unit' => 'kilogram',
                'cat_id' => 4,
                'item_stock' => 300.000,
                'item_expire_date' => null,
                'reorder_level' => 100.000,
                'min_stock_level' => 50.000,
                'max_stock_level' => 800.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 9,
                'item_code' => 'SU002',
                'item_name' => 'Brown Sugar',
                'item_description' => 'Light brown sugar for rich flavors',
                'item_unit' => 'kilogram',
                'cat_id' => 4,
                'item_stock' => 80.000,
                'item_expire_date' => null,
                'reorder_level' => 50.000,
                'min_stock_level' => 25.000,
                'max_stock_level' => 200.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Butter & Oil
            [
                'item_id' => 10,
                'item_code' => 'BU001',
                'item_name' => 'Butter (Unsalted)',
                'item_description' => 'Premium unsalted butter for baking',
                'item_unit' => 'kilogram',
                'cat_id' => 5,
                'item_stock' => 35.000,
                'item_expire_date' => '2024-12-15',
                'reorder_level' => 20.000,
                'min_stock_level' => 10.000,
                'max_stock_level' => 100.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 11,
                'item_code' => 'OI001',
                'item_name' => 'Vegetable Oil',
                'item_description' => 'Refined vegetable oil for baking',
                'item_unit' => 'liter',
                'cat_id' => 5,
                'item_stock' => 120.000,
                'item_expire_date' => '2025-03-15',
                'reorder_level' => 50.000,
                'min_stock_level' => 25.000,
                'max_stock_level' => 300.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Chocolate & Cocoa
            [
                'item_id' => 12,
                'item_code' => 'CH001',
                'item_name' => 'Dark Chocolate Chips',
                'item_description' => '60% cacao dark chocolate chips',
                'item_unit' => 'kilogram',
                'cat_id' => 6,
                'item_stock' => 45.000,
                'item_expire_date' => '2025-06-01',
                'reorder_level' => 30.000,
                'min_stock_level' => 15.000,
                'max_stock_level' => 150.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 13,
                'item_code' => 'CO001',
                'item_name' => 'Cocoa Powder',
                'item_description' => 'Dutch-processed cocoa powder',
                'item_unit' => 'kilogram',
                'cat_id' => 6,
                'item_stock' => 25.000,
                'item_expire_date' => '2025-01-31',
                'reorder_level' => 15.000,
                'min_stock_level' => 8.000,
                'max_stock_level' => 80.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Nuts & Seeds
            [
                'item_id' => 14,
                'item_code' => 'NU001',
                'item_name' => 'Almonds (Sliced)',
                'item_description' => 'Roasted sliced almonds for decorations',
                'item_unit' => 'kilogram',
                'cat_id' => 7,
                'item_stock' => 18.000,
                'item_expire_date' => '2025-05-01',
                'reorder_level' => 15.000,
                'min_stock_level' => 8.000,
                'max_stock_level' => 60.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Fruits & Fillings
            [
                'item_id' => 15,
                'item_code' => 'FR001',
                'item_name' => 'Strawberry Preserves',
                'item_description' => 'Premium strawberry fruit preserves',
                'item_unit' => 'kilogram',
                'cat_id' => 8,
                'item_stock' => 30.000,
                'item_expire_date' => '2025-02-28',
                'reorder_level' => 20.000,
                'min_stock_level' => 10.000,
                'max_stock_level' => 100.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Low stock items for testing
            [
                'item_id' => 16,
                'item_code' => 'TS001',
                'item_name' => 'Testing Item Low Stock',
                'item_description' => 'Item with low stock for testing alerts',
                'item_unit' => 'piece',
                'cat_id' => 9,
                'item_stock' => 5.000,
                'item_expire_date' => '2025-01-01',
                'reorder_level' => 25.000,
                'min_stock_level' => 15.000,
                'max_stock_level' => 100.000,
                'is_active' => true,
                'is_custom' => false,
            ],
            [
                'item_id' => 17,
                'item_code' => 'TS002',
                'item_name' => 'Testing Item Critical Stock',
                'item_description' => 'Item with critical stock level',
                'item_unit' => 'piece',
                'cat_id' => 9,
                'item_stock' => 8.000,
                'item_expire_date' => '2024-12-01',
                'reorder_level' => 30.000,
                'min_stock_level' => 20.000,
                'max_stock_level' => 100.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Expiring items for testing
            [
                'item_id' => 18,
                'item_code' => 'EX001',
                'item_name' => 'Expiring Item Soon',
                'item_description' => 'Item expiring in 15 days',
                'item_unit' => 'kilogram',
                'cat_id' => 9,
                'item_stock' => 50.000,
                'item_expire_date' => '2024-12-01',
                'reorder_level' => 25.000,
                'min_stock_level' => 15.000,
                'max_stock_level' => 100.000,
                'is_active' => true,
                'is_custom' => false,
            ],

            // Inactive item for testing
            [
                'item_id' => 19,
                'item_code' => 'IN001',
                'item_name' => 'Inactive Item',
                'item_description' => 'This item is no longer active',
                'item_unit' => 'piece',
                'cat_id' => 9,
                'item_stock' => 100.000,
                'item_expire_date' => '2025-01-01',
                'reorder_level' => 50.000,
                'min_stock_level' => 25.000,
                'max_stock_level' => 200.000,
                'is_active' => false,
                'is_custom' => false,
            ],
        ];

        foreach ($items as $item) {
            DB::table('items')->insert([
                'item_id' => $item['item_id'],
                'item_code' => $item['item_code'],
                'item_name' => $item['item_name'],
                'item_description' => $item['item_description'],
                'item_unit' => $item['item_unit'],
                'cat_id' => $item['cat_id'],
                'item_stock' => $item['item_stock'],
                'item_expire_date' => $item['item_expire_date'],
                'reorder_level' => $item['reorder_level'],
                'min_stock_level' => $item['min_stock_level'],
                'max_stock_level' => $item['max_stock_level'],
                'is_active' => $item['is_active'],
                'is_custom' => $item['is_custom'],
                'last_updated' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }
    }
}